config/routes.rb
Spree::Core::Engine.add_routes do

  namespace :admin do
    resources :contacts
    resources :topics
  end

  resources :contacts, :only => [:new, :create]

  get 'contact' => 'contacts#new'
end

app/models/spree/contact.rb
require 'spree/core/validators/email'
module Spree
  class Contact < ActiveRecord::Base
    belongs_to :topic
    # accepts_nested_attributes_for :topic
    # delegate_belongs_to :topic, :id
    # delegates_attributes_to :topic
    # delegate_belongs_to :topic, :topic_id
    # accepts_nested_attributes_for :topic

    validates :name, :topic_id, :message, :presence => true
    validates :email, email: true

    after_save do
      ContactMailer.notification(self).deliver # to submitter
      ContactMailer.confirmation(self).deliver # to admin
    end
  end
end

app/models/spree/topic.rb
require 'spree/core/validators/email'
module Spree
  class Topic < ActiveRecord::Base
    has_many :contacts
    validates :title, :email, :presence => true
    validates :email, email: true
  end
end

app/controllers/spree/admin/contacts_controller.rb
module Spree
  module Admin
    class ContactsController < ResourceController
      helper 'spree/admin/contacts'
  
      respond_to :html
      
      def create
        @contact = Contact.new(params[:contact])
        if no_bees and @contact.save
          redirect_to root_path, :notice => Spree.t("success_message")
        else
          render :new
        end
      end
      
      protected
      def no_bees
        params[:easy_honey].blank?
      end

    end
  end
end

app/controllers/spree/admin/topics_controller.rb
module Spree
  module Admin
    class TopicsController < ResourceController
      respond_to :html
    end
  end
end

app/controllers/spree/contacts_controller.rb
class Spree::ContactsController < Spree::StoreController

  helper "spree/products"

  def new
    @contact = Spree::Contact.new
    render 'spree/contacts/contact'
  end


  def create
    @contact = Spree::Contact.new(permit_attributes)

    if @contact.save
      #todo mailer here

      redirect_to(spree.root_path, :notice => Spree.t('contacts.notices.success'))
    else
      render 'spree/contacts/contact'
    end
  end

  private
  def permit_attributes
    params.require(:contact).permit!
  end

  def accurate_title
    Spree.t('contacts.new.contact')
  end

end

app/helpers/spree/admin/contacts_helper.rb
module Spree
  module Admin
    module ContactsHelper
      def link_to_show(resource, options={})
        link_to_with_icon 'link', Spree.t(:display), object_url(resource), options
      end
      
      def link_to_resend(resource, options={})
        link_to_with_icon 'envelope', Spree.t(:resend), object_url(resource), options
      end
    end
  end
end

app/views/spree/admin/contacts/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t("spree.contacts.index.title") %>
<% end %>

<% content_for :page_actions do %>
    <li><%= button_link_to Spree.t(:go_to_topics_list), admin_topics_url, :icon => 'icon-arrow-right' %></li>
    <li id="new_topic_link">
      <%= button_link_to Spree.t(:new_topic), new_object_url, {:remote => true, :icon => 'icon-plus', :id => 'admin_new_topic'} %>
    </li>
<% end %>

<div id="new_topic" data-hook></div>

<table class="index">
  <colgroup>
    <col style="width: 23%" />
    <col style="width: 23%" />
    <col style="width: 23%" />
    <col style="width: 23%" />
    <col style="width: 10%" />
  </colgroup>
  <thead>
  <tr>
    <th><%= Spree.t("name") %></th>
    <th><%= Spree.t("email") %></th>
    <th><%= Spree.t("topic") %></th>
    <th><%= Spree.t("sent") %></th>
    <th class="actions"></th>
  </tr>
  </thead>
  <tbody>
  <% @collection.each do |contact| %>
      <tr class="<%= cycle('odd', 'even') %>" id="dom_id contact">
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.try(:topic).try(:title) %></td>
        <td><%= contact.created_at %></td>
        <td class="actions">
          <%= link_to_show contact, :no_text => true %>
          <%= link_to_delete contact, :no_text => true %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/contacts/show.html.erb
<% content_for :sidebar_title do %>
    <%= Spree.t(:contact_action) %>
<% end %>

<% content_for :page_actions do %>
    <li><%= button_link_to Spree.t(:back_to_contacts_list), admin_contacts_url, :icon => 'icon-arrow-left' %></li>
    <li><%= button_link_to Spree.t(:go_to_topics_list), admin_topics_url, :icon => 'icon-arrow-right' %></li>
    <li id="new_topic_link">
      <%= button_link_to Spree.t(:new_topic), new_object_url, {:remote => true, :icon => 'icon-plus', :id => 'admin_new_topic'} %>
    </li>
<% end %>

<% content_for :sidebar do %>
    <nav class="menu">
      <ul class="">
        <li><%# link_to_resend @contact %></li>
      </ul>
    </nav>

<% end %>

<h3>Contact <%= Spree.t("sent") %> <%= l @contact.created_at %></h3>
<p><strong><%= Spree.t("name") %>&nbsp;:&nbsp;</strong><%= @contact.name %></p>
<p><strong><%= Spree.t("email") %>&nbsp;:&nbsp;</strong><%= @contact.email %></p>
<p><strong><%= Spree.t("topic") %>&nbsp;:&nbsp;</strong><%= @contact.try(:topic).try(:title) %></p>
<p><strong><%= Spree.t("order_number") %>&nbsp;:&nbsp;</strong><%= @contact.try(:order_number) %></p>
<p><strong><%= Spree.t("message") %>&nbsp;:&nbsp;</strong><%= @contact.message %></p>

app/views/spree/admin/shared/_contact_sub_menu.html.erb
<% content_for :sub_menu do %>
    <ul id="sub_nav" data-hook="admin_product_sub_tabs" class="inline-menu">
      <%= tab :contacts, :match_path => '/contacts' %>
      <%= tab :topics, :match_path => '/topics' %>
    </ul>
<% end %>

app/views/spree/admin/topics/_form.html.erb
<div class="four columns">
  <%= f.field_container :title do %>
      <%= f.label :title, t(".title") %>
      <br/>
      <%= f.text_field :title %>
  <% end %>
</div>

<div class="four columns">
  <%= f.field_container :email do %>
      <%= f.label :email, t(".email") %>
      <br/>
      <%= f.text_field :email %>
  <% end %>
</div>

app/views/spree/admin/topics/edit.html.erb
<%= render :partial => 'spree/admin/shared/contact_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @topic } %>

<% content_for :page_title do %>
    <%= Spree.t(:edit) %>
<% end %>

<%= form_for [:admin, @topic] do |f| %>
    <fieldset class="fieldset-state">
      <legend><%= Spree.t('activerecord.models.label') %></legend>
      <%= render :partial => 'form', :locals => { :f => f } %>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </fieldset>
<% end %>

app/views/spree/admin/topics/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t("spree.topics.index.title") %>
<% end %>

<% content_for :page_actions do %>
    <li><%= button_link_to Spree.t(:back_to_contacts_list), admin_contacts_url, :icon => 'icon-arrow-left' %></li>
    <li id="new_topic_link">
      <%= button_link_to Spree.t(:new_topic), new_object_url, {:remote => true, :icon => 'icon-plus', :id => 'admin_new_topic'} %>
    </li>
<% end %>

<div id="new_topic" data-hook></div>

<% if @collection.any? %>
    <table class="index">
      <colgroup>
        <col style="width: 40%"/>
        <col style="width: 40%"/>
        <col style="width: 10%"/>
      </colgroup>
      <thead>
      <tr>
        <th><%= Spree.t("title") %></th>
        <th><%= Spree.t("email") %></th>
        <th class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @collection.each do |topic| %>
          <tr class="<%= cycle('odd', 'even') %>" id="dom_id contact">
            <td><%= topic.title %></td>
            <td><%= topic.email %></td>
            <td class="actions">
              <%= link_to_edit topic, :no_text => true %>
              &nbsp;
              <%= link_to_delete topic, :no_text => true %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="no-object-found"><%= t(:no_results) %></div>
<% end %>

app/views/spree/admin/topics/new.html.erb
<%= render :partial => 'spree/admin/shared/contact_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @topic } %>

<% content_for :page_title do %>
    <%= Spree.t(:new) %>
<% end %>

<%= form_for [:admin, @topic] do |f| %>
    <fieldset class="fieldset-state">
      <legend><%= Spree.t('activerecord.models.label') %></legend>
      <%= render :partial => 'form', :locals => { :f => f } %>
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    </fieldset>
<% end %>

app/views/spree/admin/topics/new.js.erb
$("#new_topic").html('<%= escape_javascript(render :template => "spree/admin/topics/new", :formats => [:html], :handlers => [:erb]) %>');
<% unless Rails.env.test? %>
$('.select2').select2();
<% end %>
$("#table-filter").hide();
$("#admin_new_topic").parent().hide();

app/views/spree/admin/topics/show.html.erb
<% content_for :sidebar_title do %>
    <%= t(:topic_action) %>
<% end %>
<% content_for :sidebar do %>
    <nav class="menu">
      <ul class="sidebar">
        <li>
          <%= link_to_with_icon 'icon-list', t("topic_list"), collection_url() %>
        </li>
        <li><%= link_to_show @topic %></li>
        <li><%= link_to_resend @topic %></li>
      </ul>
    </nav>

<% end %>

<h3><%= @topic.title %></h3>
<p><strong><%= t(:title) %>&nbsp;:&nbsp;</strong><%= @topic.name %></p>
<p><strong><%= t(:email) %>&nbsp;:&nbsp;</strong><%= @topic.email %></p>